### ISSUE TITLE
Really usefull!

### ISSUE THREAD

**Issue by betoxx** [sebastiansulinski/three-state-checkbox#1]
But how to know the ids checked from all the groups?

How to display inputs with checked prop and reflect to the checkboxMaster?

Thanks!

**Comment by sebastiansulinski** [comment]
Hi @betoxx,

Each group is associated with one button - if you have multiple record sets - simply use one group only on the page - it will submit all ids to the master button and be associated with one master checkbox.

There is no way to submit different groups to one master button as that would defeat the purpose of the grouping. I hope that makes sense.

Also please remember that it doesn't matter if the checkboxes are wrapped within different `form` elements - as we only look for items with specific `data-*` attributes - so if you have them in separate `form` tags - they will still be collected if they use the same group.
