### ISSUE TITLE
Option to switch between change an click event

### ISSUE THREAD

**Issue by massic80** [sebastiansulinski/three-state-checkbox#3]
Hi,
I'm using your plugin within an accordion which kills the click event while it's bubbling up to the wrapper, hence the clicks on the master don't work.
I manually switched the click events in your code into change events, and everything works as expected.
I'd like to know why you chose to use click event instead of change (it wouldn't allow users to toggle the checkboxes with the keyboard), but I'd ask you to add an option to allow users to switch between using click and change event, for backwards compatibility.

**Comment by sebastiansulinski** [comment]
Hi @massic80 - thanks for pointing that out.
I've changed the `click` to `check` now in version `1.2.0`

**Comment by massic80** [comment]
I'm glad to see that you appreciated and applied my solution :)
I wonder whether this may introduce regressions in active production environments... I was thinking of a setup parameters with the desired event, and something like

`settings.event = "click";
if (parameters.iWantChange)
settings.event = "change";
$(this).on(settings.event, function`...

This is probably excess of zeal, current solution probably works like a charm also on older environments and it's more efficient, but I'd spend two minutes in wondering it...
