### ISSUE TITLE
Master checkbox should be updated on landing

### ISSUE THREAD

**Issue by massic80** [sebastiansulinski/three-state-checkbox#6]
At the moment, the _master_ checkbox isn't rendered with the correct status on initialization:
- when at least one of the _record_ checkboxes is checked, it should get the indeterminate state
- if all of them are it should be checked
- if none is checked the master should stay blank
Everything works correctly later, hence I figure out the library just misses a verification on initialization phase, identical to those performed on change.

**Comment by sebastiansulinski** [comment]
This has been resolved in #2fcfbb2
