### ISSUE TITLE
Incoherent statuses of Master checkbox

### ISSUE THREAD

**Issue by massic80** [sebastiansulinski/three-state-checkbox#7]
When starting from all _record_ checkboxes unchecked and checking all of them one by one, _master_ checkbox begins with `indefinite===false` and `checked===false`, gets the `indefinite===true` when the first checkbox is checked and gets `checked===true` when all of them are finally checked. At this moment, its `indefinite` goes back to `false`. This is the correct procedure.
The problem is: when the user un-checks one of the checked _record_ checkboxes, the _master_ keeps the `selected===true`. This is the same state we had before the last "checking", but _master_ checkbox has different attributes. It should always be unchecked when the checked _record_ checkboxes were less than all of them.

**Comment by sebastiansulinski** [comment]
What browser are you experiencing this problem in?

**Comment by massic80** [comment]
I figure out it's everywhere. I just checked with Chrome and Firefox.
In your example, http://jquery-three-state-checkbox.ssdtutorials.com
It _looks like_ not checked, since it's styled for indefinite, but it's checked, as reported by
document.getElementsByClassName("checkboxMaster")[0].checked

I'm noticing that you just pushed something :)

**Comment by sebastiansulinski** [comment]
Please check latest version 1.2.1 - this should resolve this issue for you.
